services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library_db
      - SPRING_DATASOURCE_USERNAME=library_user
      - SPRING_DATASOURCE_PASSWORD=library_pass_123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8088:8088"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=library_user
      - POSTGRES_PASSWORD=library_pass_123
      - POSTGRES_DB=library_db
    ports:
      - "5432:5432"